### ISSUE TITLE
Climatology Window Error?

### ISSUE THREAD

**Issue by Nereus32** [seandepagnier/weather_routing_pi#250]
When I compute a route in ov50 on my Mac, GRIB and Climatology windows open, as usual, but the Climatology window is blank and won't close. However, this does not happen if I manually open Climatology and letting the window load before computing the route. Then everything works as expected. Don't know if this is an issue with Climatology or WR...

**Comment by rgleason** [comment]
This should not be happening. Can you drag a screenshot of when it is blank, into your post?
When Climatology is initially open, is it normal?  When does it go blank?

**Comment by Nereus32** [comment]
It is normal if Climatology is initially open, yes. It only does it when WR opens Climatology... It runs through all its files, but then never finishes opening the window.
![Screen Shot](https://user-images.githubusercontent.com/39605258/57958176-bef95080-78b3-11e9-8cbf-3193977ae4cd.png)
![With_Climatology_Open](https://user-images.githubusercontent.com/39605258/57958180-c15baa80-78b3-11e9-8597-70e615f85551.png)

**Comment by rgleason** [comment]
Nereus, this is MacOS. Where did you get the climatology plugin?  Give me the link please.
Is the plugin about 7mb in size or is it much smaller?
Did you have to download data files through the internet?

I have tried Climatology, downloaded from the website downloads  for Windows, and it is about 7mb. There were about 7 files that were corrupted and Climatology downloaded those successfully. Then I ran a routing across the atlantic to Falmouth, using a grib file at first, then climatology.  I turned on Climatology after weatherrouting and it made no difference.

You have a corrupted or bad version of climatology I think.
![Screenshot (80)](https://user-images.githubusercontent.com/2363959/57961270-caf90880-78db-11e9-838e-bd2a2386b4b2.png)

**Comment by Nereus32** [comment]
I'm pretty sure I downloaded and built it off of Pavel Kalian's repository. It built fine and works on it own. Has all the data included. 

I'm not sure that Climatology is bad, though. I sent my WR installer pkg to someone else for them to try with their own version of Climatology (don't know where that one came from) and he had the same issue.
[Weather_routing-Plugin-ov50_1.13.0.pkg.zip](https://github.com/seandepagnier/weather_routing_pi/files/3193535/Weather_routing-Plugin-ov50_1.13.0.pkg.zip)

**Comment by rgleason** [comment]
Build it off of Sean's Repository please.  Or preferably download it from the downloads page.

**Comment by Nereus32** [comment]
"Not yet available" on the downloads page. I'll try Sean's and get back to you.

**Comment by Nereus32** [comment]
Same result with the one compiled from Sean's repository.
![Screen Shot 2019-05-18 at 2 39 30 PM](https://user-images.githubusercontent.com/39605258/57975300-f54dd300-797a-11e9-9ac5-b85922a56601.png)

When you open Climatology after, it clears the stuck window.

**Comment by seandepagnier** [comment]
Is this macosx specific?

**Comment by rgleason** [comment]
Yes, it does not happen in win

**Comment by Nereus32** [comment]
To recap, I discovered I didn't build Climatology. I had downloaded the Climatology_pi from the the OpenCPN.org site link. So, I thought I'd try my own just now. I built direct from this repository and installed. The issue is gone. So the issue may be in the "official" version online.

I have another Mac friend I sent mine to. Hopefully he'll check it out soon and let me know if it is working correctly. It all seems ok on mine.

**Comment by rgleason** [comment]
Is this resolved now by a local build?
Would a new build for the download version help so that we can close this?

**Comment by rgleason** [comment]
Nereus32
Can you please download Climatolgy from the main Website Downloads page?

Ron has recompiled it using the latest code and PR #69 

If that fixes your problem, please close this report!!!!  Thanks.

**Comment by Nereus32** [comment]
I didn't solve the issues, however, since we believe it's an issue with Climatology and not Weather_Routing, I will close this and research a different way.

**Comment by rgleason** [comment]
OK, thanks.  Please advise re the issue on Climatology Issues.
